version: '3.7'

services:

  train-radar:
    build: .
    environment:
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_SYNC=${DATABASE_SYNC}
      - DEVICE_KEY=${DEVICE_KEY}
      - WEBSOCKET_EVENT=${WEBSOCKET_EVENT}
    ports:
      - ${PORT}:3000
    restart: always
    networks:
      - train-radar

networks:
  train-radar:
    external:
      name: "${NETWORK_NAME:-train-radar-dev}"
